apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-st-test-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: efs-csi
  volumeMode: Filesystem
