apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-st-test-efs-pvc
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: efs-csi
  volumeMode: Filesystem
